### ISSUE TITLE
Process::fromShellCommandline($cmd, $cwd); fails

### ISSUE THREAD

**Issue by gertvdb** [matteosister/GitElephant#164]
The function `Process::fromShellCommandline($cmd, $cwd);` doesn't work in latest release (v4.1.0)

<img width="1418" alt="Screenshot 2020-03-19 at 20 30 45" src="https://user-images.githubusercontent.com/7106435/77107597-3b534780-6a21-11ea-9bbb-5d461bd65a1a.png">

I'm running this via a composer script. Changing it to `$process = new Process($cmd, $cwd);` seem to work.

**Comment by GenieTim** [comment]
Can you tell me the version of the Symfony Process component you have installed? 
This function was setup in GitElephant v4.1.0, in the newest version, and potentially introduced an incompatibility between Symfony Process v4 and v5. 
Does it work if you force composer to install GitElephant < v4.1.0?

**Comment by jurgenhaas** [comment]
I'm seeing the same thing and here I'm using symfony/process version 3.4.38 - this is within a Drupal 8 context, hence the symfony 3.x dependency.

**Comment by GenieTim** [comment]
I see. After minor research, I found out: Since v3.3, Process can be instantiated with an array. The string method we use is deprecated since Symfony 4.2 – relocated to be used via `Process::fromShellCommandline` – and removed in 5.0. Ergo, either we exclude elder versions or introduce case distinction – that latter is my recommendation and implementation in #165. May I ask someone of you to test whether the fix works for you?

**Comment by gertvdb** [comment]
The fix seems to work for me. Thanks
